---
title: "REPDATA_CoursePro1"
output: html_document
date: "2024-04-03"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Unzip data to obtain a cvs file

```{r}
library("data.table")
library(ggplot2)

unzip("C:/Users/Maria Vargas/OneDrive/Desktop/RStudio/repdata_data_activity.zip")
activityDT <- read.csv("activity.csv")
activityDTS <- data.table::fread(input = "data/activity.csv")

names(activityDT)
summary(activityDT)
str(activityDT)
```

## What is the mean total number of the steps taken per day

```{r}
Total_Steps <- activityDTS[, c(lapply(.SD, sum, na.rm = FALSE)), .SDcols = c("steps"), by = .(date)] 

head(Total_Steps, 10)


ggplot(Total_Steps, aes(x = steps)) +
    geom_histogram(fill = "blue", binwidth = 1000) +
    labs(title = "Daily Steps", x = "Steps", y = "Frequency")

Total_Steps[, .(Mean_Steps = mean(steps, na.rm = TRUE), Median_Steps = median(steps, na.rm = TRUE))]

```

## What is the average daily activity pattern?
```{r}
IntervalDT <- activityDTS[, c(lapply(.SD, mean, na.rm = TRUE)), .SDcols = c("steps"), by = .(interval)] 

ggplot(IntervalDT, aes(x = interval , y = steps)) + geom_line(color="blue", size=1) + labs(title = "Avg. Daily Steps", x = "Interval", y = "Avg. Steps per day")


IntervalDT[steps == max(steps), .(max_interval = interval)]


```


## Imputing missing values

```{r}
nrow(activityDTS[is.na(steps),])


activityDTS[is.na(steps), "steps"] <- activityDT[, c(lapply(.SD, median, na.rm = TRUE)), .SDcols = c("steps")]


data.table::fwrite(x = activityDTS, file = "data/tidyData.csv", quote = FALSE)

Total_Steps <- activityDTS[, c(lapply(.SD, sum)), .SDcols = c("steps"), by = .(date)] 


Total_Steps[, .(Mean_Steps = mean(steps), Median_Steps = median(steps))]


ggplot(Total_Steps, aes(x = steps)) + geom_histogram(fill = "blue", binwidth = 1000) + labs(title = "Daily Steps", x = "Steps", y = "Frequency")

```

## Are there differences in activity patterns between weekdays and weekends?
```{r}
activityDTS <- data.table::fread(input = "data/activity.csv")
activityDTS[, date := as.POSIXct(date, format = "%Y-%m-%d")]
activityDTS[, `Day of Week`:= weekdays(x = date)]
activityDTS[grepl(pattern = "Monday|Tuesday|Wednesday|Thursday|Friday", x = `Day of Week`), "weekday or weekend"] <- "weekday"
activityDTS[grepl(pattern = "Saturday|Sunday", x = `Day of Week`), "weekday or weekend"] <- "weekend"
activityDTS[, `weekday or weekend` := as.factor(`weekday or weekend`)]
head(activityDTS, 10)


activityDTS[is.na(steps), "steps"] <- activityDTS[, c(lapply(.SD, median, na.rm = TRUE)), .SDcols = c("steps")]
IntervalDT <- activityDTS[, c(lapply(.SD, mean, na.rm = TRUE)), .SDcols = c("steps"), by = .(interval, `weekday or weekend`)] 

ggplot(IntervalDT , aes(x = interval , y = steps, color=`weekday or weekend`)) + geom_line() + labs(title = "Avg. Daily Steps by Weektype", x = "Interval", y = "No. of Steps") + facet_wrap(~`weekday or weekend` , ncol = 1, nrow=2)
```
